# Generated by Django 3.2.19 on 2023-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='bikes',
            field=models.CharField(choices=[('N/A', 'N/A'), ('RD', 'Road'), ('MTB', 'Mtb'), ('GRVL', 'Gravel'), ('FIX', 'Fixie'), ('TR', 'Touring'), ('BMX', 'Bmx'), ('HYB', 'Hybrid')], default='N/A', max_length=20),
        ),
    ]
