# Generated by Django 3.2.19 on 2023-07-02 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='forumpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forum_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
