# Generated by Django 3.2.19 on 2023-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20230702_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='bars',
            field=models.CharField(choices=[('Unknown', 'Unknwon'), ('Flat', 'Flat'), ('Drop', 'Drop'), ('Alt', 'Alt'), ('Other', 'Other')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='gears',
            field=models.CharField(choices=[('Unknown', 'Unknwon'), ('FIXED', 'FIXED'), ('1X', '1X'), ('2X', '2X'), ('3X', '3X'), ('Other', 'Other')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='bikes',
            field=models.CharField(choices=[('Unknown', 'none'), ('RD', 'Road'), ('MTB', 'Mtb'), ('GRVL', 'Gravel'), ('FIX', 'Fixie'), ('TR', 'Touring'), ('BMX', 'Bmx'), ('HYB', 'Hybrid')], default='Unknown', max_length=20),
        ),
    ]
