# Generated by Django 3.2.19 on 2023-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20230707_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='bikes',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Road', 'Road'), ('Mtb', 'Mtb'), ('Gravel', 'Gravel'), ('Fixie', 'Fixie'), ('Touring', 'Touring'), ('BMX', 'BMX'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], default='Unknown', max_length=20),
        ),
    ]
