# Generated by Django 3.2.19 on 2023-07-08 10:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_forumpost_bikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='second_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='third_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
