# Generated by Django 3.2.19 on 2023-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20230708_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='bars',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Flat', 'Flat'), ('Drop', 'Drop'), ('Alt', 'Alt'), ('Other', 'Other')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='bikes',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Road', 'Road'), ('Gravel', 'Gravel'), ('CX', 'CX'), ('Touring', 'Touring'), ('MTB', 'MTB'), ('Downhill', 'Downhill'), ('Fixie', 'Fixie'), ('Commute', 'Commute'), ('BMX', 'BMX'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='gears',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Fixed', 'Fixed'), ('1X', '1X'), ('2X', '2X'), ('3X', '3X'), ('Hub', 'Hub'), ('Other', 'Other')], default='N/A', max_length=20),
        ),
    ]
