# Generated by Django 3.2.19 on 2023-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_messages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='bars',
            field=models.CharField(choices=[('Other', 'Other'), ('Flat', 'Flat'), ('Drop', 'Drop'), ('Alt', 'Alt')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='bikes',
            field=models.CharField(choices=[('Other', 'Other'), ('Road', 'Road'), ('Gravel', 'Gravel'), ('CX', 'CX'), ('Touring', 'Touring'), ('MTB', 'MTB'), ('Downhill', 'Downhill'), ('Fixie', 'Fixie'), ('Commute', 'Commute'), ('BMX', 'BMX'), ('Hybrid', 'Hybrid')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='gears',
            field=models.CharField(choices=[('Other', 'Other'), ('Fixed', 'Fixed'), ('1X', '1X'), ('2X', '2X'), ('3X', '3X'), ('Hub', 'Hub')], default='Other', max_length=20),
        ),
    ]
